compLink: https://www.worldcubeassociation.org/competitions/TrojanSpring2024
compName: test comp
competitorList:
- Adam Scarchilli
- Anders Jacobsen
- Ansel de Jong
- Ash Messner
- Blaze Palmer
- "C\xE9sar Eduardo Loredo Rubio"
- Chris Kristo
- Cole Brown
- Colin Pierce
- Connor McKahan
- Croix Pierre Lomont
- Doug Li
- Eli Katz
- Emmett Wager
- Ethan Crawford
- Gibson Diemand
- Henry J. Buehrer
- Hunter Mackler
- Ivan C. Michalik
- Jack DeCapua
- Joel Aber
- Juan De La Rosa
- Justin Jang
- Katherine Aber
- Kayla Brown
- Kelton Eric William Kyro
- Lorelei Aiedail Kuusisto
- Mason Langenderfer
- Mohamedali Hassan
- Natapong Kanema
- Owen B. Hakala
- Owen Bettin
- Quinn Lawson
- Santiago Zamora Rodriguez
- Sujan Feist
- Thomas Borchelt
- Tyler Rose
- Wesley Barwinski
- Zachary Garber
- Zoe Marihugh
currentCompetitor:
  competitor: Colin Pierce
  event: PyraR1
eventsList:
  2x2: 1
  3x3: 3
  Pyra: 1
  Skewb: 1
